### PR TITLE
some text edits

### PR DESCRIPTION
**Pull request by bradleypeabody**
@kyzer-davis Here are some initial notes and updates.

I'll fill in the UUIDv7 stuff more soon.

### CODE REVIEW

**Comment by kyzer-davis** [comment]
I approve the edits. The SHOULD/MUST for 802 IEEE MAC makes. Please edit that text before the merge. I will open a new pull for the k-sortable (k-ordering) definition text.

**Comment by ramsey** [comment]
> I'll fill in the UUIDv7 stuff more soon.

Nice! So, you've decided to add a v7?

**Comment by bradleypeabody** [comment]
@ramsey Yeah, we're filling in more info in the draft, but general idea is to add 3 new types, each with different trade-offs.  v6 is basically http://gh.peabody.io/uuidv6/ and is made to be simple to implement.  v7 will use a bit more complicated of an encoding scheme but can support variable-precision sub-second times (so JS implementations can encode/decode with millisecond precision, and others can encode/decode with nanosecond precision and the implementations remain compatible), and v8 is basically a loose version where you can do more or less whatever you want and implementations which didn't create the value just treat it as an opaque bunch of bytes.

so v6 is simple, v7 supports arbitrary time precisions, and v8 is the most flexible.

**Comment by ramsey** [comment]
Cool. I'll read the latest. I haven't been able to focus on it or contribute like I wanted. I'm glad to see the progress!

**Pull request merged**
