### PR TITLE
more work on UUIDv7 field, still wip but getting there

### PR DESCRIPTION
**Pull request by bradleypeabody**
@kyzer-davis This isn't quite ready to merge in but I wanted to let you know what I have so far on this and see if you had any feedback.

I'm trying to see if there is existing prior art that describes the encoding technique I'm proposing for the sub-second timestamp.

I split up the bit layout into separate diagrams covering encoding and decoding.  It's more verbose but I think it's much more clear.   Since the decoding only allows extraction of the timestamp, and the encoding includes certain fields but allows implementations to put them in various places, I figured it was easiest to describe it as "this is how you decode, and encoding is anything that is compatible with it - here are some useful examples".

### CODE REVIEW

**Comment by fabiolimace** [comment]
@bradleypeabody,

I think you can encode the sub-second part into a [fixed-point number](https://inst.eecs.berkeley.edu/~cs61c/sp06/handout/fixedpt.html). Using a fixed-point number is easy to [encode and decode](http://ee.sharif.edu/~asic/Tutorials/Fixed-Point.pdf). You multiply to encode and divide to decode. But the sub-second value must be a fraction between 0 and 1.

I was confused about the field `unixts`. Is it reserved for seconds or milliseconds? If it is for seconds, it could be generated UUIDs up to the year 8,921,373 A.D. (2**48/60/60/24/365.25 + 1970). If it was for milliseconds, someone could be confused with the word `sub-second` instead of `sub-millisecond` (like me).

I spent part of today thinking about how it could be implemented in Python. Fortunately, this language supports big numbers. I imagined on two structures: one with sub-second precision and another with sub-millisecond precision. See them below.

I moved the rest of this comment to the issue #11.

Best regards!

**Comment by fabiolimace** [comment]
Today I implemented this simple generator in python to test the concept:

```python
#!/usr/bin/python3
#
# @date: 2021-03-06
# @author: fabiolimace
#

from uuid import UUID
from time import time
from random import randint

TOTAL_BITS=128
VERSION_BITS = 4
VARIANT_BITS = 2

SEC_BITS=38
SUBSEC_S_BITS=0
SUBSEC_MS_BITS=10
SUBSEC_US_BITS=20
SUBSEC_NS_BITS=30

SLICE_MASK_0 = 0xffffffffffff00000000000000000000
SLICE_MASK_1 = 0x0000000000000fff0000000000000000
SLICE_MASK_2 = 0x00000000000000003fffffffffffffff

def uuid7(t=None, subsec_bits=SUBSEC_NS_BITS):
	
	if t == None:
		t = time()
	
	i = int(t) # integer part
	f = t - int(t) # fractional part
	
	sec = i
	subsec = int(f * (2 ** subsec_bits))
	
	node_bits = (TOTAL_BITS - SEC_BITS - subsec_bits)
	
	uuid_sec = sec << (subsec_bits + node_bits)
	uuid_subsec = subsec << node_bits
	uuid_node = randint(0, (2 ** node_bits))
	
	uuid_int = uuid_sec | uuid_subsec | uuid_node # 122 bits
	uuid_int = __add_version__(uuid_int) # 128 bits

	return UUID(int=uuid_int)
	
def uuid7_s(t:None):
	return uuid7(t, SUBSEC_S_BITS)
	
def uuid7_ms(t:None):
	return uuid7(t, SUBSEC_MS_BITS)

def uuid7_us(t:None):
	return uuid7(t, SUBSEC_US_BITS)

def uuid7_ns(t:None):
	return uuid7(t, SUBSEC_NS_BITS)

def __add_version__(uuid_int):
	
	slice_mask_0 = SLICE_MASK_0 >> (VERSION_BITS + VARIANT_BITS)
	slice_mask_1 = SLICE_MASK_1 >> (VARIANT_BITS)
	slice_mask_2 = SLICE_MASK_2

	slice_0 = (uuid_int & slice_mask_0) << (VERSION_BITS + VARIANT_BITS)
	slice_1 = (uuid_int & slice_mask_1) << (VARIANT_BITS)
	slice_2 = (uuid_int & slice_mask_2)
	
	uuid_output = slice_0 | slice_1 | slice_2
	uuid_output = uuid_output & 0xffffffffffff0fff3fffffffffffffff # clear version
	uuid_output = uuid_output | 0x00000000000070008000000000000000 # apply version

	return uuid_output

def __rem_version__(uuid_int):
	
	slice_0 = (uuid_int & SLICE_MASK_0) >> (VERSION_BITS + VARIANT_BITS)
	slice_1 = (uuid_int & SLICE_MASK_1) >> (VARIANT_BITS)
	slice_2 = (uuid_int & SLICE_MASK_2)
	
	uuid_output = slice_0 | slice_1 | slice_2
	
	return uuid_output

def get_sec(uuid):
	uuid_int = __rem_version__(uuid.int)
	uuid_sec = uuid_int >> (TOTAL_BITS - SEC_BITS)	
	return uuid_sec
	
def get_subsec(uuid, subsec_bits=SUBSEC_NS_BITS):
	node_bits = (TOTAL_BITS - SEC_BITS - subsec_bits)
	subsec_mask = 0xffffffffffffffffffffffffffffffff >> SEC_BITS
	uuid_int = __rem_version__(uuid.int) & subsec_mask
	uuid_subsec = (uuid_int >> node_bits)
	return uuid_subsec / (2**subsec_bits)

def list():

	print()
	print("## LIST()")
	
	for i in range(10):
		t = time()
		u = uuid7(t)
		i = int(t)
		f = t - int(t)
		sec = get_sec(u)
		subsec = get_subsec(u)
		print(u, i, sec, f, subsec)

def test():

	t = time()
	u = uuid7(t)
	sec = get_sec(u)
	subsec = get_subsec(u)
	
	print()
	print("## TEST()")
	
	print("time in:        ", t)
	print("time out:       ", sec + subsec)
	print("seconds in:     ", int(t))
	print("seconds out:    ", sec)
	print("subseconds in:  ", t - int(t))
	print("subseconds out: ", subsec)

list()
test()

```

OUTPUT: 

```
## LIST()
6043e9c3-d192-7580-83b6-bf2822668ca9 1615063491 1615063491 0.8186392784118652 0.8186392784118652
6043e9c3-d197-7e80-87cb-5b96cee6999f 1615063491 1615063491 0.8187241554260254 0.8187241554260254
6043e9c3-d19a-7a00-868b-e0fe66f4ed54 1615063491 1615063491 0.8187656402587891 0.8187656402587891
6043e9c3-d19d-79c0-8fd2-dd62577b9c64 1615063491 1615063491 0.8188111782073975 0.8188111782073975
6043e9c3-d1a1-7ac0-8297-093a11e87e50 1615063491 1615063491 0.8188731670379639 0.8188731670379639
6043e9c3-d1a4-7780-8553-19646fc975a7 1615063491 1615063491 0.818915843963623 0.818915843963623
6043e9c3-d1a6-7040-89f2-a645d0c39977 1615063491 1615063491 0.8189394474029541 0.8189394474029541
6043e9c3-d1a8-7140-8e6f-d07c44e938ad 1615063491 1615063491 0.8189709186553955 0.8189709186553955
6043e9c3-d1aa-7c80-8c4b-6c1188a5b7c2 1615063491 1615063491 0.8190121650695801 0.8190121650695801
6043e9c3-d1ac-7ec0-825d-8074c92efbf6 1615063491 1615063491 0.819044828414917 0.819044828414917

## TEST()
time in:         1615063491.8190813
time out:        1615063491.8190813
seconds in:      1615063491
seconds out:     1615063491
subseconds in:   0.8190813064575195
subseconds out:  0.8190813064575195

```

**Comment by bradleypeabody** [comment]
@kyzer-davis Alright, I think I've filled in the missing parts for UUIDv7 and it's looking pretty good.  I just tried to run the RFC converting thingy and it timed out - can't tell if that's my doc or just the tool. (The XML itself looks valid though.)

Please have a look and I'll merge this into master, and we can discuss what's left to get this submitted.

**Comment by kyzer-davis** [comment]
Sorry for the delay!
#12 opened to merge into this branch then merge #10 down to master if it looks good.

**Pull request merged**
